# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: seodj
google_analytics: seodj
comments: true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: seodj

description: Stylish Jekyll Theme
author:
  name: 서동진
  email: seodj@nhnent.com
  github: seodj
  twitter: 
  pinterest: 
  linkedin: 
  bio: be the best
  email_md5: 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
