# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
---
layout: default
title: Home
---

{% include intro.html %}

<section class="post-list">
  <div class="container">

    <h2>Writing..</h2>

    {% for post in paginator.posts %}
      <article class="post-item">
        <p><span class="post-meta">{{ post.date | date: "%b %-d, %Y" }}</span>  ??<strong><a class="post-link" href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a></strong> ??<span> {{ post.content | strip_html | truncatewords: 40 }}</span> <a class="post-link readmore" href="{{ post.url | prepend: site.baseurl }}">Read more</a></p>
      </article>
    {% endfor %}
  </div>

  <div class="container">
    {% include pagination.html %}
  </div>
</section>



# Build settings
markdown: kramdown

encoding: utf-8
highlighter: rouge
highlighter: pygments