# Site settings
title: Seodj's blog
header-img: img/home-bg.jpg
email: riker7@naver.com
description: "Hello This is Seodj's blog"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]